name: Tagged Release


on:
  push:
    tags:
      - "v*"


jobs:
  tagged-release:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build file with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed --icon "images/icons/valocker-enabled.ico" --add-data "data;data/" --add-data "images;images/" --collect-all "customtkinter" --distpath dist/ VALocker.pyw

      - name: Create ZIP file
        run: |
          mkdir zip_content/VALocker
          cp dist/VALocker.exe zip_content/VALocker/
          cp data zip_content/VALocker/ -Recurse
          cp images zip_content/VALocker/ -Recurse
          rm zip_content/VALocker/data/instalocker.py
          rm zip_content/VALocker/images/readme_images/ -Recurse
          Compress-Archive -Path zip_content/VALocker/ -DestinationPath VALocker.zip
          rm zip_content -Recurse -Force

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            VALocker.zip
          
