name: Tagged Release

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build file with PyInstaller
        run: |
          pyinstaller build.spec

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            dist/VALocker.exe
