name: VirusTotal Scan on Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  download-and-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Release Asset
      uses: dsaltares/fetch-gh-release-asset@1.1.2
      with:
        repo: "E1Bos/VALocker"
        version: "tags/${{ github.event.release.tag_name }}"
        file: "*.exe"
        target: "./release-assets"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: VirusTotal Scan
      uses: crazy-max/ghaction-virustotal@v4
      with:
        vt_api_key: ${{ secrets.VIRUSTOTAL_API_KEY }}
        files: |
          ./release-assets/*.exe